#shell
alias cd..="cd .."
alias la="ls -AlGh"
alias ll="ls -lGh"
alias cls="clear"
alias c="clear"

alias d="lsd -l"
alias ll="ls -l"

alias df="df -h"
alias du="du -hc"
alias mp="multipass"

# emacs shortcuts
alias e="emacsclient -n" # send file to emacs
alias et="emacsclient -t" # open emacs in terminal
alias emacs="emacs -nw  --eval '(menu-bar-mode -1)' -Q" # open pure emacs in terminal
alias doom="~/.emacs.d/bin/doom"
alias emacs-daemon="launchctl start gnu.emacs.daemon"

# git helpers
alias gpp="gup && gp"
alias gbv="git branch -avv"
alias glog="git log --graph --pretty=format:'%C(auto)%h%d%Creset %s %Cgreen(%cr) %C(blue)<%an>%Creset' --abbrev-commit --all"
alias gdc="git diff --cached"
alias gdh="git diff HEAD"
alias gba="git branch -avv"

# switch on/off word wraping in terminal lines
alias wrapon="tput rmam"
alias wrapoff="tput smam"

# go helpers
alias gogrep="grep -r --include \*.go"
function replace_import_path() {
    from=$(echo $1 | sed -e 's/[\/&]/\\&/g')
    to=$(echo $2 | sed -e 's/[\/&]/\\&/g')
    find . -name '*.go' -exec sed -i '' -e "s/$from/$to/g" {} \;
}

function run() {
    for dir in script scripts; do
        for suffix in "" ".sh" ".go"; do
            cmd=$(git rev-parse --show-toplevel)/$dir/$1$suffix
            export GIT_ROOT=$(git rev-parse --show-toplevel)
            if test -f $cmd; then
                if [[ "${cmd: -3}" == ".go" ]]; then
                    go run $cmd ${@:2}
                else
                    $cmd ${@:2}
                fi
                return $?
    	    fi
        done
    done
    echo "no command $1 found"
}

function cd-git-root() {
    cd $(git rev-parse --show-toplevel)
}
alias cdr="cd-git-root"

alias stm_cli=/Applications/STMicroelectronics/STM32Cube/STM32CubeProgrammer/STM32CubeProgrammer.app/Contents/MacOs/bin/STM32_Programmer_CLI
alias cdz="cd ~/code/zig"
alias cdc="cd ~/code"
alias cdd="cd ~/code/dot"
